### ISSUE TITLE
Hi Chuck!

### ISSUE THREAD

**Issue by bekirby** [csschwe/kvm-stuff#1]
Trying to follow your instructions for creating the bridge interface. Got the bridge to work and I can connect/ssh to the running KVM Ubuntu image, but I wacked my local interface in the process. I am unable to connect to the internet so had to restore from backup to fix it : )

I can connect to the internet though from my Ubuntu VM.

In your /etc/netplan/01-netcfg.yaml example - is enp7s0 your existing interface or is it a new interface? I used 'eno1' since that is my interface but maybe that is wrong?

bk@NUC8i7BEH:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 94:c6:91:a3:85:5c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.7/24 brd 192.168.1.255 scope global dynamic noprefixroute eno1
       valid_lft 86376sec preferred_lft 86376sec
    inet6 fe80::ba18:5019:e643:163c/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

**Comment by csschwe** [comment]
Yes, it should be eno1 in your configuration.  I assume you used your Interface IP and gateway in br0?

**Comment by bekirby** [comment]
I got an Ubuntu VM up and running and can ssh to it which was my goal for today. Just had to use the right interfaces. Thanks.
